services:
  - type: web
    name: ai-fitness-myth-buster-frontend
    runtime: nodejs
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    rootDir: frontend
    envVars:
      - key: REACT_APP_API_ENDPOINT
        value: https://ai-fitness-myth-buster-backend.onrender.com

  - type: web
    name: ai-fitness-myth-buster-backend
    runtime: nodejs
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    rootDir: backend
    envVars:
      - key: PORT
        value: 5000